export enum EOrderStatus {
  PENDING = 'PENDING',
  PREPARING = 'PREPARING',
  SHIPPING = 'SHIPPING',
  DELIVERED = 'DELIVERED',

  SUCCESS = 'SUCCESS',
  CANCELLED = 'CANCELLED',
  RETURNED = 'RETURNED',
}